In [1]:
import os
import pandas as pd

Now, to calculate Anchoring Score methods that come to mind are -
i) Boundaries per ball
ii) Normal Strike Rate
iii) Percentage Runs from Boundaries.
iv) Weighted average of Dot balls played and Boundary scoring balls

In [2]:
data={
    "Name":[],
    "Playing Style Score":[]
}

In [3]:
for player in os.listdir("E:/Cricket Prediction Project/PLAYERS"):
    df=pd.read_csv("E:/Cricket Prediction Project/PLAYERS/"+player) 
    if sum(df["balls_faced"]) == 0 or sum(df["runs_scored"])==0:
        continue
    data["Name"].append(player[:-4])
    data["Playing Style Score"].append((sum(df["fours"])*4+sum(df["sixes"])*6)/sum(df["runs_scored"]) * 100)

In [4]:
df=pd.DataFrame(data)

In [5]:
df_condensed = pd.read_csv("E:/Cricket Prediction Project/Condensed.csv", index_col=0)

In [6]:
ls=list(df["Name"])

In [7]:
ls

['A Balbirnie',
 'A Maregwede',
 'A Saud',
 'A Sharafu',
 'A Vala',
 'Aamir Kaleem',
 'AB de Villiers',
 'Abdul Shakoor',
 'Abid Ali',
 'AC Voges',
 'AD Hales',
 'AD Mathews',
 'Adnan Akmal',
 'Adnan Mufti',
 'Afif Hossain',
 'Afsar Zazai',
 'Aftab Ahmed',
 'Agha Salman',
 'Ahmed Shehzad',
 'AJ Finch',
 'AJ Hall',
 'AJ Ireland',
 'AJ Redmond',
 'AJ Strauss',
 'AJ Turner',
 'AK Perera',
 'Alok Kapali',
 'AM Blignaut',
 'AM McCarthy',
 'AM Rahane',
 'Amjad Ali',
 'AN Cook',
 'AN Petersen',
 'AP Devcich',
 'AR Adams',
 'AR Berenger',
 'AR White',
 'Asad Shafiq',
 'Asghar Stanikzai',
 'Asif Ali',
 'AT Carey',
 'AT Rayudu',
 'Azhar Ali',
 'B Bhandari',
 'B Sharki',
 'BA King',
 'BA Stokes',
 'Babar Azam',
 'Basil Hameed',
 'Bazid Khan',
 'BB McCullum',
 'BC Lara',
 'Bilal Asif',
 'BJ Haddin',
 'BJ Hodge',
 'BJ Watling',
 'BKG Mendis',
 'BM Duckett',
 'BOP Fernando',
 'BR McDermott',
 'BRM Taylor',
 'BT Foakes',
 'C de Grandhomme',
 'C Hemraj',
 'C Jonker',
 'C Munro',
 'C Zhuwao',
 'CA Lynn',
 'CA Pujara',
 'CD McMillan',
 'CH Gayle',
 'CJ Anderson',
 'CJ Chibhabha',
 'CJ Ferguson',
 'CJA Amini',
 'CK Coventry',
 'CK Kapugedera',
 'CL Cairns',
 'CL White',
 'CM McBride',
 'CMW Read',
 'CR Ervine',
 'CS Baugh',
 'CS MacLeod',
 'D Cleaver',
 'D Elgar',
 'D Ganga',
 'D Khanal',
 'D Lakshan',
 'D Mongia',
 'D Murphy',
 'D Ramdin',
 'D Wiese',
 'DA Gunawardene',
 'DA Miller',
 'DA Warner',
 'DAS Gunaratne',
 'DC Thomas',
 'DE Bernard',
 'DE Budge',
 'DG Brownlie',
 'DI Joyce',
 'DJ Bravo',
 'DJ Malan',
 'DJ Mitchell',
 'DJG Sammy',
 'DJM Short',
 'DM Bravo',
 'DM de Silva',
 'DP Conway',
 'DR Smith',
 'DS Lehmann',
 'DS Weerakkody',
 'E Lewis',
 'EC Joyce',
 'EJG Morgan',
 'EMDY Munaweera',
 'F Behardien',
 'F du Plessis',
 'FA Allen',
 'Faisal Iqbal',
 'Fakhar Zaman',
 'Fayyaz Ahmed',
 'FDM Karunaratne',
 'FH Allen',
 'FRJ Coleman',
 'FY Fazal',
 'G Chapple',
 'G Gambhir',
 'G Malla',
 'GA Manou',
 'GC Smith',
 'GC Wilson',
 'GD Drummond',
 'GD Phillips',
 'GF Linde',
 'GH Worker',
 'Ghulam Shabber',
 'GJ Bailey',
 'GJ Delany',
 'GJ Hopkins',
 'GJ Maxwell',
 'GM Strydom',
 'GS Ballance',
 'GSNFG Jayasuriya',
 'Gurkeerat Singh',
 'H Davids',
 'H Klaasen',
 'H Masakadza',
 'Habibul Bashar',
 'Haider Ali',
 'Hammad Azam',
 'Hannan Sarkar',
 'Haris Sohail',
 'Hashmatullah Shahidi',
 'Hazratullah',
 'HC Brook',
 'HD Rutherford',
 'HDRL Thirimanne',
 'HE van der Dussen',
 'HH Dippenaar',
 'HH Gibbs',
 'HH Pandya',
 'HJH Marshall',
 'HM Amla',
 'HM Nicholls',
 'HP Rinke',
 'Hussain Talat',
 'HWR Cartwright',
 'I Kaia',
 'Ibrahim Zadran',
 'ID Blackwell',
 'Iftikhar Ahmed',
 'Iftikhar Anjum',
 'IJL Trott',
 'Imam-ul-Haq',
 'Imran Farhat',
 'Imran Nazir',
 'Imrul Kayes',
 'Inzamam-ul-Haq',
 'IR Bell',
 'Ishan Kishan',
 'J Blackwood',
 'J Charles',
 'J Louw',
 'J Mubarak',
 'JA Burns',
 'JA Morkel',
 'JA Rudolph',
 'JA Simpson',
 'JAH Marshall',
 'Javed Ahmadi',
 'Javed Omar',
 'JC Buttler',
 'JDS Neesham',
 'JE Root',
 'JH Kallis',
 'JJ Roy',
 'JJ van der Wath',
 'JL Carter',
 'JL Denly',
 'JL Ontong',
 'JM Bairstow',
 'JM How',
 'JM Vince',
 'JN Hamilton',
 'JN Mohammed',
 'JNK Shannon',
 'JP Bray',
 'JP Duminy',
 'JP Inglis',
 'Junaid Siddique',
 'JWM Dalrymple',
 'K Bhurtel',
 'K Zondo',
 'KA Hope',
 'KA Pollard',
 'KC Brathwaite',
 'KD Karthik',
 'KDK Vithanage',
 'KED Carroll',
 'KH Pandya',
 'KH Prajapati',
 'Khalid Latif',
 'Khurram Khan',
 'Khurram Manzoor',
 'Khushdil Shah',
 'KIC Asalanka',
 'KJ Coetzer',
 "KJ O'Brien",
 'KK Nair',
 'KL Rahul',
 'KM Dabengwa',
 'KM Jadhav',
 'KMC Bandara',
 'KNA Bandara',
 'KOA Powell',
 'Krishna Chandran',
 'KS Lokuarachchi',
 'KS Williamson',
 'KY Ottley',
 'L Louwrens',
 'L Ronchi',
 'L Siaka',
 'L Sreekumar',
 'L Tucker',
 'L Vincent',
 'LD Chandimal',
 'LD Madushanka',
 'LN Roche',
 'LR Naylor',
 'LRPL Taylor',
 'LS Livingstone',
 'M Shumba',
 'M van Jaarsveld',
 'MA Carberry',
 'MA Jones',
 'MA Leask',
 'MA Vermeulen',
 'Mahedi Hasan',
 'Mahmudullah',
 'MB Loye',
 'MC Henriques',
 'MD Gunathilaka',
 'MD Shanaka',
 'MDKJ Perera',
 'ME Sanuth',
 'ME Trescothick',
 'MG Neser',
 'MH Cross',
 'MHW Papps',
 'MJ Cosgrove',
 'MJ Fourie',
 'MJ Guptill',
 'MJ North',
 'MJ Prior',
 'MK Pandey',
 'MK Tiwary',
 'ML Cummins',
 'ML Nkala',
 'MM Ali',
 'MM Iqbal',
 'MN Samuels',
 'MN van Wyk',
 'MN Waller',
 'MNK Fernando',
 'Mohammad Aadil Alam',
 'Mohammad Ashraful',
 'Mohammad Boota',
 'Mohammad Hafeez',
 'Mohammad Haris',
 'Mohammad Naim',
 'Mohammad Rizwan',
 'Mohammad Shahzad',
 'Mohammed Qasim',
 'Mominul Haque',
 'Mosaddek Hossain',
 'MP Stoinis',
 'MP Vaughan',
 'MR Marsh',
 'MS Chapman',
 'MS Dhoni',
 'MS Sinclair',
 'MS Tshabalala',
 'MS Wade',
 'Muhammad Usman',
 'Mushfiqur Rahim',
 'Mushfiqur Rahman',
 'MV Boucher',
 'MW Machan',
 'N Boje',
 'N Dickwella',
 'N Pooran',
 'N Rana',
 'Nafees Iqbal',
 'Najibullah Zadran',
 'Naseem Khushi',
 'Nasir Jamal',
 'Nasir Jamshed',
 'Nawroz Mangal',
 'Nazmul Hossain Shanto',
 'Nazmul Hossain',
 'ND McKenzie',
 'NE Bonner',
 'Nestor Dhamba',
 'NJ Astle',
 "NJ O'Brien",
 'Noor Ali Zadran',
 'NT Broom',
 'Nurul Hasan',
 'O Davidson',
 'P Khadka',
 'P Mustard',
 'P Nissanka',
 'P Sarraf',
 'PA Jaques',
 'PARP Perera',
 'PC de Silva',
 'PD Collingwood',
 'PD Macchi',
 'PD McGlashan',
 'PD Salt',
 'PG Fulton',
 'PHKD Mendis',
 'PJ Forrest',
 'PJ Hughes',
 'PJ Moor',
 'PL Mommsen',
 'PR Stirling',
 'PS Masvaure',
 'PSP Handscomb',
 'Q de Kock',
 'R Clarke',
 'R Mutumbami',
 'R Powell',
 'RA Jones',
 'Raees Ahmadzai',
 'Rahmat Shah',
 'RAJ Smith',
 'Rajin Saleh',
 'Rameez Shahzad',
 'RAP Nissanka',
 'RD Berrington',
 'RD Gaikwad',
 'RD Jacobs',
 'RG Sharma',
 'RJ Nicol',
 'RK Paudel',
 'RN Lewis',
 'Rohan Mustafa',
 'RR Hendricks',
 'RR Pant',
 'RR Rossouw',
 'RR Sarwan',
 'RR Watson',
 'RS Kaluwitharana',
 'RT Crandon',
 'RV Uthappa',
 'RWT Key',
 'S Badrinath',
 'S Chanderpaul',
 'S Chattergoon',
 'S Dhawan',
 'S Samarawickrama',
 'S Vesawkar',
 'SA Yadav',
 'Sabbir Rahman',
 'Salman Faris',
 'Samiullah Shenwari',
 'Saqib Ali',
 'Saqlain Haider',
 'Sarfraz Ahmed',
 'Saud Shakeel',
 'SB Bangar',
 'SB Styris',
 'SC Ganguly',
 'SC Getkate',
 'SC Kuggeleijn',
 'SD Heazlett',
 'SD Hope',
 'SE Marsh',
 'Shafiqullah',
 'Shaiman Anwar',
 'Shakib Al Hasan',
 'Sharjeel Khan',
 'Shoaib Khan',
 'Shoaib Malik',
 'Shubman Gill',
 'Shuvagata Hom',
 'SI Kamea',
 'Sikandar Raza',
 'Simi Singh',
 'SJ Cameron',
 'SK Raina',
 'SM Ervine',
 'SO Dowrich',
 'SO Hetmyer',
 'Sohaib Maqsood',
 'Soumya Sarkar',
 'SP Fleming',
 'SP Patil',
 'SPD Smith',
 'SR Tendulkar',
 'SS Iyer',
 'SS Pathirana',
 'SSJ Brooks',
 'STR Binny',
 'SV Samson',
 'SW Ambris',
 'SW Billings',
 'SW Poynter',
 'T Duffin',
 'T Maruma',
 'T Taibu',
 'Tamim Iqbal',
 'Taufeeq Umar',
 'TD Paine',
 'TJ Friend',
 'TK Musakanda',
 'TL Seifert',
 'TM Head',
 'TMK Mawoyo',
 'TP Ura',
 'TSS Mackintosh',
 'TT Samaraweera',
 'Tushar Imran',
 'TWM Latham',
 'Umar Akmal',
 'Umar Amin',
 'Usman Ghani',
 'UT Khawaja',
 'V Aravind',
 'V Kohli',
 'V Shankar',
 'V Sibanda',
 'VB van Jaarsveld',
 'VR Iyer',
 'VRV Singh',
 'W Jaffer',
 'W Madhevere',
 'Waheed Ahmed',
 'Washington Sundar',
 'WIA Fernando',
 'WTS Porterfield',
 'WU Tharanga',
 'WW Hinds',
 'XM Marshall',
 'Yasir Hameed',
 'YK Pathan',
 'Younis Khan',
 'Yuvraj Singh',
 'Z Crawley',
 'Zubayr Hamza']

In [8]:
df_sorted=df_condensed.query('Name in @ls')

In [9]:
df_sorted

,Name,Right arm Fast,Right arm Medium,Left arm Fast,Left arm Medium,Right arm off-spinner,Right arm Legbreak,Left arm Orthodox,Left arm Chinaman,Hitting Score,Anchoring Score
0,A Balbirnie,"[778, 1066, 26]","[169, 234, 6]","[111, 156, 3]","[3, 5, 0]","[485, 611, 16]","[259, 329, 5]","[286, 351, 7]","[36, 58, 0]",To be calculated,To be calculated
6,A Maregwede,"[19, 41, 1]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[11, 9, 0]","[0, 0, 0]","[24, 39, 1]","[0, 0, 0]",To be calculated,To be calculated
8,A Saud,"[26, 66, 2]","[0, 0, 0]","[0, 0, 0]","[9, 9, 0]","[3, 9, 1]","[0, 0, 0]","[8, 11, 0]","[0, 0, 0]",To be calculated,To be calculated
9,A Sharafu,"[18, 44, 2]","[23, 28, 2]","[0, 0, 0]","[0, 0, 0]","[10, 12, 0]","[9, 3, 0]","[46, 63, 0]","[0, 0, 0]",To be calculated,To be calculated
10,A Vala,"[302, 462, 7]","[5, 6, 0]","[8, 13, 0]","[15, 24, 0]","[109, 193, 5]","[33, 47, 0]","[150, 226, 6]","[0, 0, 0]",To be calculated,To be calculated
...,...,...,...,...,...,...,...,...,...,...,...
620,YK Pathan,"[270, 260, 14]","[35, 34, 1]","[62, 50, 3]","[0, 0, 0]","[101, 90, 2]","[20, 25, 1]","[96, 87, 1]","[0, 0, 0]",To be calculated,To be calculated
621,Younis Khan,"[1537, 2425, 79]","[307, 331, 2]","[225, 367, 9]","[22, 28, 0]","[623, 669, 13]","[164, 166, 0]","[433, 598, 18]","[0, 0, 0]",To be calculated,To be calculated
622,Yuvraj Singh,"[2062, 2360, 57]","[431, 530, 9]","[236, 425, 17]","[28, 36, 1]","[740, 886, 8]","[171, 187, 4]","[371, 432, 10]","[10, 10, 1]",To be calculated,To be calculated
623,Z Crawley,"[49, 41, 1]","[0, 0, 0]","[21, 21, 1]","[0, 0, 0]","[0, 0, 0]","[10, 7, 0]","[2, 2, 0]","[0, 0, 0]",To be calculated,To be calculated
624,Zubayr Hamza,"[22, 22, 1]","[4, 15, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[5, 9, 0]","[0, 0, 0]",To be calculated,To be calculated

In [10]:
df_sorted=df_sorted.reset_index()
df=df.reset_index()

In [11]:
k=pd.concat([df_sorted, df.drop('Name', axis='columns')], axis=1, join='inner')

In [12]:
k.columns

Index(['index', 'Name', 'Right arm Fast', 'Right arm Medium', 'Left arm Fast',
       'Left arm Medium', 'Right arm off-spinner', 'Right arm Legbreak',
       'Left arm Orthodox', 'Left arm Chinaman', 'Hitting Score',
       'Anchoring Score', 'index', 'Playing Style Score'],
      dtype='object')

In [13]:
k=k.drop('Hitting Score', axis='columns')
k=k.drop('Anchoring Score', axis='columns')
k=k.drop('index', axis='columns')

In [14]:
k.to_csv('E:/Cricket Prediction Project/Final Data.csv')

In [15]:
k

,Name,Right arm Fast,Right arm Medium,Left arm Fast,Left arm Medium,Right arm off-spinner,Right arm Legbreak,Left arm Orthodox,Left arm Chinaman,Playing Style Score
0,A Balbirnie,"[778, 1066, 26]","[169, 234, 6]","[111, 156, 3]","[3, 5, 0]","[485, 611, 16]","[259, 329, 5]","[286, 351, 7]","[36, 58, 0]",45.980254
1,A Maregwede,"[19, 41, 1]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[11, 9, 0]","[0, 0, 0]","[24, 39, 1]","[0, 0, 0]",48.148148
2,A Saud,"[26, 66, 2]","[0, 0, 0]","[0, 0, 0]","[9, 9, 0]","[3, 9, 1]","[0, 0, 0]","[8, 11, 0]","[0, 0, 0]",43.478261
3,A Sharafu,"[18, 44, 2]","[23, 28, 2]","[0, 0, 0]","[0, 0, 0]","[10, 12, 0]","[9, 3, 0]","[46, 63, 0]","[0, 0, 0]",47.169811
4,A Vala,"[302, 462, 7]","[5, 6, 0]","[8, 13, 0]","[15, 24, 0]","[109, 193, 5]","[33, 47, 0]","[150, 226, 6]","[0, 0, 0]",42.546584
...,...,...,...,...,...,...,...,...,...,...
468,YK Pathan,"[270, 260, 14]","[35, 34, 1]","[62, 50, 3]","[0, 0, 0]","[101, 90, 2]","[20, 25, 1]","[96, 87, 1]","[0, 0, 0]",62.328767
469,Younis Khan,"[1537, 2425, 79]","[307, 331, 2]","[225, 367, 9]","[22, 28, 0]","[623, 669, 13]","[164, 166, 0]","[433, 598, 18]","[0, 0, 0]",36.665660
470,Yuvraj Singh,"[2062, 2360, 57]","[431, 530, 9]","[236, 425, 17]","[28, 36, 1]","[740, 886, 8]","[171, 187, 4]","[371, 432, 10]","[10, 10, 1]",54.038034
471,Z Crawley,"[49, 41, 1]","[0, 0, 0]","[21, 21, 1]","[0, 0, 0]","[0, 0, 0]","[10, 7, 0]","[2, 2, 0]","[0, 0, 0]",58.536585
472,Zubayr Hamza,"[22, 22, 1]","[4, 15, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[5, 9, 0]","[0, 0, 0]",45.161290